name: "Publish Neuron site"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12

      - name: Build neuron site
        run: |
          nix run github:srid/neuron/164956f --version
          nix run github:srid/neuron/164956f neuron -o out/ gen --pretty-urls
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
