name: "Publish Neuron site"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - main
jobs:
  neuron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build neuron site 🔧
      # the neuron version should match the one we uses locally, i.e. in neuron.nix
      run: |
        mkdir -p .neuron/output && touch .neuron/output/.nojekyll
        docker run -v $PWD:/notes sridca/neuron:1.9.35.0 neuron gen --pretty-urls
    - name: Deploy to gh-pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .neuron/output/
        cname: voyd.de
